import {useState} from 'react';
import {Home, FlaskConical, BriefcaseBusiness, FileText, Mail, ArrowRight, ArrowUpRight, GitBranch, Heart, X, RotateCcw, Check, Copy, Sun, Moon, ChevronRight} from 'lucide-react';
import {portfolioProjects} from './projects';
const base=import.meta.env.BASE_URL;
const samples=[
 {title:'Scientific Software Engineer',company:'Example Scientific',place:'San Francisco',skills:'Python · React · Scientific workflows',reason:'Connect software delivery with scientific R&D.'},
 {title:'Implementation Consultant',company:'Example Lab Systems',place:'Boston',skills:'SQL · LIMS · Customer workflows',reason:'Turn laboratory requirements into working systems.'},
 {title:'Applied AI Engineer',company:'Example AI Studio',place:'New York',skills:'Python · RAG · API development',reason:'Build grounded tools around evidence and review.'}
];
function DemoDeck(){const [index,setIndex]=useState(0);const [liked,setLiked]=useState(0);const [message,setMessage]=useState('Try the recommendation deck.');const job=samples[index];
 function decide(like){setLiked(n=>n+(like?1:0));setMessage(like?'Saved to your demo shortlist.':'Passed. Next recommendation.');setIndex(n=>n+1);}
 return <div className="demo-deck"><div className="demo-top"><span>INTERACTIVE DEMO</span><span>{liked} liked · {Math.min(index,3)}/3 reviewed</span></div>{job?<><div className="demo-company"><FlaskConical size={18}/>{job.company}<span>Fictional role</span></div><h3>{job.title}</h3><p>{job.place}</p><div className="demo-skills">{job.skills}</div><p className="demo-reason">{job.reason}</p><div className="demo-controls"><button onClick={()=>decide(false)}><X size={17}/>Pass</button><button onClick={()=>decide(true)}><Heart size={17}/>Like this job</button></div></>:<div className="demo-finished"><Check size={28}/><h3>That's your shortlist.</h3><p>{liked} saved. In the local app, choose Apply Assist to prepare your résumé and review the application.</p><button onClick={()=>{setIndex(0);setLiked(0);setMessage('Demo reset.');}}><RotateCcw size={16}/>Try again</button></div>}<span className="sr-only" role="status">{message}</span></div>
}
function FormulationDemo(){const [concentrate,setConcentrate]=useState(30);return <div className="formulation-demo"><div className="demo-top"><span>FORMULATION WORKBENCH</span><span>Illustrative mass balance</span></div><h3>Change the blend.<br/>See the composition.</h3><div className="blend-values"><div><span>Protein concentrate</span><strong>{concentrate}<small>%</small></strong></div><div><span>Carbohydrate base</span><strong>{100-concentrate}<small>%</small></strong></div><div><span>Blend protein</span><strong>{(concentrate*.8).toFixed(1)}<small>%</small></strong></div></div><label htmlFor="blend">Protein concentrate in blend <span>{concentrate}%</span></label><input id="blend" aria-label="Protein concentrate percentage" type="range" min="0" max="100" step="1" value={concentrate} onChange={e=>setConcentrate(Number(e.target.value))}/><p>Example inputs: 80% protein concentrate + 0% protein base. This preview shows mass balance; the full project adds constraints, optimisation and evidence review.</p></div>}
export default function LivingPortfolio(){const [selected,setSelected]=useState(1);const [copied,setCopied]=useState(false);const [light,setLight]=useState(false);const project=portfolioProjects[selected];
 async function copyEmail(){try{await navigator.clipboard.writeText('charlieqi2017@gmail.com');setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setCopied(false);}}
 return <div className={`living-site${light?' light':''}`}>
 <a className="skip-link" href="#projects">Skip to projects</a>
 <aside className="rail" aria-label="Portfolio navigation"><a href="#home" className="portrait-link" aria-label="Charlie Qi home"><img src={`${base}profile-photo.jpeg`} alt="Charlie Qi"/></a><nav><a href="#home" aria-label="Home" title="Home"><Home/></a><a href="#projects" aria-label="Projects" title="Projects"><FlaskConical/></a><a href="#experience" aria-label="Experience" title="Experience"><BriefcaseBusiness/></a><a href="mailto:charlieqi2017@gmail.com?subject=Resume%20request" aria-label="Request résumé" title="Request résumé"><FileText/></a><a href="#contact" aria-label="Contact" title="Contact"><Mail/></a></nav><button className="theme-button" aria-label={light?'Use dark theme':'Use light theme'} title="Change theme" onClick={()=>setLight(!light)}>{light?<Moon/>:<Sun/>}</button></aside>
 <main>
 <section className="opening" id="home">
 <img className="hero-art" src={`${base}living-systems-hero.png`} alt="" fetchPriority="high"/>
 <header className="masthead"><a href="#home">Charlie Qi<span>AI ENGINEERING / BIOTECH R&amp;D</span></a><a className="availability" href="#contact">Open to the next chapter <ArrowUpRight size={14}/></a></header>
 <div className="hero-copy"><div className="eyebrow">/ LIVING SYSTEMS</div><h1>Science,<br/><em>engineered.</em></h1><p>Scientific experience.<br/>Software that makes it useful.</p><div className="hero-actions"><a className="primary" href="#projects">Explore my systems <ArrowRight size={19}/></a><a className="github-link" href="https://github.com/Charlie-Qi394" target="_blank" rel="noreferrer"><GitBranch size={24}/> GitHub</a></div></div>
 </section>
 <section className="featured" aria-label="Featured project"><div className="featured-copy"><span className="eyebrow muted">{selected===1?'FLAGSHIP PROJECT':'PROJECT SPOTLIGHT'}</span><h2>{project.title}</h2><p>{selected===0?'Discover a role. Find the right résumé. Keep the decision yours.':'From ingredient evidence to a reviewable formulation. Scientific constraints, optimisation and traceable decisions in one workspace.'}</p><a className="text-link" href={project.href} target="_blank" rel="noreferrer">View project <ArrowRight size={18}/></a></div><div className="featured-visual">{selected===0?<DemoDeck/>:<FormulationDemo/>}</div></section>
 <div className="opening-bottom"><div className="project-switch" aria-label="Featured project selection">{[1,0].map((i,position)=><button key={i} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span>{String(position+1).padStart(2,'0')}</span>{i===0?'Job Application OS':'Formulation OS'}</button>)}</div><a href="mailto:charlieqi2017@gmail.com?subject=Resume%20request">Résumé available on request <ArrowUpRight size={15}/></a></div>
 <section id="projects" className="content-section"><div className="section-heading"><div><span className="eyebrow">01 / SELECTED WORK</span><h2>Built to be used.<br/><em>Open to be inspected.</em></h2></div><p>Seven projects across scientific software, AI tools and applied machine learning. Explore the decisions behind the interfaces.</p></div><div className="projects-grid">{[portfolioProjects[1],portfolioProjects[0],...portfolioProjects.slice(2)].map((p,i)=><article className="work-item" key={p.title}><div className="work-meta"><span>{String(i+1).padStart(2,'0')}</span><a href={p.href} aria-label={`Source code for ${p.title}`} target="_blank" rel="noreferrer"><ArrowUpRight size={23}/></a></div><h3><a href={p.href} target="_blank" rel="noreferrer">{p.title}</a></h3><p className="work-stack">{p.stack}</p><p>{p.bullets[0]}</p><details><summary>Engineering details <ChevronRight size={15}/></summary><p>{p.bullets[1]||p.bullets[0]}</p><a className="text-link" href={p.href} target="_blank" rel="noreferrer">Read the repository <ArrowUpRight size={15}/></a></details></article>)}</div></section>
 <section className="content-section experience" id="experience"><div className="experience-photo"><img src={`${base}profile-photo.jpeg`} alt="Charlie Qi" loading="lazy"/><span>CHARLIE QI / MELBOURNE</span></div><div><span className="eyebrow">02 / TWO DISCIPLINES. ONE PRACTICE.</span><h2>The lab taught me<br/><em>what matters.</em><br/>Code lets me build it.</h2><p>Ten years in biotech and nutrition R&amp;D, manufacturing and regulated product decisions. A Master of Computer Science specialising in AI. I bring that domain context into the software I build.</p><div className="practice-row"><span>01</span><div><h3>Start with the real workflow</h3><p>Suppliers, specifications, laboratory evidence and the people making decisions.</p></div></div><div className="practice-row"><span>02</span><div><h3>Make the reasoning inspectable</h3><p>Grounded AI where it helps. Deterministic calculations where precision matters. Review before consequential actions.</p></div></div><a className="text-link" href="mailto:charlieqi2017@gmail.com?subject=Resume%20request">Request my résumé <ArrowRight size={18}/></a></div></section>
 <section className="contact-section" id="contact"><span className="eyebrow">03 / THE NEXT CHAPTER</span><h2>Let's build something<br/><em>worth understanding.</em></h2><p>Applied AI · Scientific software · Python &amp; full-stack engineering</p><div className="contact-buttons"><a className="primary" href="mailto:charlieqi2017@gmail.com">Start a conversation <ArrowUpRight size={18}/></a><button className="copy-email" onClick={copyEmail}>{copied?<Check size={17}/>:<Copy size={17}/>}<span role="status">{copied?'Email copied':'Copy email'}</span></button></div><p className="resume-note">Résumé available on request.</p></section>
 <footer><span>© {new Date().getFullYear()} Charlie Qi</span><a href="https://github.com/Charlie-Qi394" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a><a href="#home">Back to top <ArrowUpRight size={14}/></a></footer>
 </main></div>
}
