export const projectNarratives = [
  {
    title: "Integrated Nutrition Formulation Optimisation Platform",
    filter: "Product software",
    label: "Domain software",
    summary: "A full-stack formulation workspace for reviewed Excel/CSV/PDF nutrient ingestion, constrained bulk formulation optimisation, premix design and reviewable product decisions.",
    stack: "React · TypeScript · FastAPI · PostgreSQL · SciPy/HiGHS · Gemini",
    build: "I modelled ingredient and specification versions, added evidence ingestion and formulator review, then connected linear optimisation, mass-balance modelling and deterministic risk bands.",
    proof: "This is the clearest example of turning a real biotech R&D workflow into software with data models, calculations, validation and auditability.",
    href: "https://github.com/Charlie-Qi394/integrated-formulation-optimisation-tool",
    questions: ["How do I keep calculations deterministic?", "How do I preserve version history?", "Where should AI assist rather than decide?"],
  },
  {
    title: "CareOps AI - MCP-Powered Operations Assistant",
    filter: "AI systems",
    label: "Agent tooling",
    summary: "An operations assistant that gives an LLM controlled access to validated business tools.",
    stack: "TypeScript · Node.js · React · MCP · PostgreSQL · Prisma · Docker",
    build: "I implemented tools for client search, worker availability, compliance checks, address updates and appointment rescheduling, with RBAC, validation, confirmation-gated writes and audit logging.",
    proof: "It demonstrates practical agent architecture: the model can reason about a task, but tools enforce permissions and business rules before anything changes.",
    href: "https://github.com/Charlie-Qi394/careops-ai",
    questions: ["What can the model read?", "Which actions require confirmation?", "How can a change be audited later?"],
  },
  {
    title: "AI Regulatory Knowledge Assistant",
    filter: "AI systems",
    label: "RAG application",
    summary: "A document-grounded assistant for searching technical and regulatory material with citations.",
    stack: "Python · FastAPI · Streamlit · PostgreSQL/pgvector · OpenAI · LangGraph",
    build: "I built TXT/PDF/DOCX ingestion, chunking, embeddings, pgvector retrieval, grounded answer generation, citations, query history, a LangGraph workflow and CSV evaluation.",
    proof: "It shows the complete RAG loop and a conservative boundary: when evidence is weak, the assistant should say so instead of inventing an answer.",
    href: "https://github.com/Charlie-Qi394/ai-regulatory-knowledge-assistant",
    questions: ["Is the evidence sufficient?", "Can the answer be traced to sources?", "How do I evaluate retrieval and faithfulness?"],
  },
  {
    title: "FridgePeace Shared-Household Food Management PWA",
    filter: "Product software",
    label: "Product build",
    summary: "A practical PWA that combines shared household workflows with an AI-assisted food scanning experience.",
    stack: "React · FastAPI · PostgreSQL · PWA patterns · AI-assisted workflow",
    build: "I focused on a user-facing workflow: shared ownership, item tracking and a clear interface around an everyday problem rather than a standalone model demo.",
    proof: "It demonstrates product thinking, frontend workflow design and the ability to connect AI assistance to a concrete user task.",
    href: "https://github.com/Charlie-Qi394/fridgepeace-portfolio",
    questions: ["What is the user trying to finish?", "What should be automated?", "What happens when the model is uncertain?"],
  },
  {
    title: "Seq2Seq Recipe Generation with Attention",
    filter: "ML / CV",
    label: "NLP model",
    summary: "A PyTorch sequence-generation project comparing LSTM encoder-decoder models with and without attention.",
    stack: "Python · PyTorch · LSTM · attention · beam search · BLEU/METEOR",
    build: "I implemented preprocessing, vocabulary construction, batching, packed sequences, masked attention and beam-search decoding, then evaluated overlap and ingredient-grounding behaviour.",
    proof: "The project taught me to pair model improvements with task-specific evaluation rather than treating one metric as the whole story.",
    href: "https://github.com/Charlie-Qi394/seq2seq-recipe-generation-nlp",
    questions: ["What did attention change?", "Where did hallucination remain?", "How would I compare a Transformer?"],
  },
  {
    title: "Computer Vision Classification and Segmentation",
    filter: "ML / CV",
    label: "Computer vision",
    summary: "A progression from classical image processing to CNN classification and semantic segmentation.",
    stack: "Python · TensorFlow/Keras · CNNs · FCN · U-Net · FPN-style models",
    build: "I implemented Harris and Canny methods, compared library baselines, trained CIFAR-100 CNNs and experimented with FCN, U-Net and FPN-style segmentation designs.",
    proof: "It demonstrates controlled experimentation: establish a baseline, change meaningful variables, measure the effect and explain the trade-off.",
    href: "https://github.com/Charlie-Qi394/computer-vision-cnn-segmentation",
    questions: ["What is the difference between classification and segmentation?", "How did I measure improvement?", "What is the cost of a larger model?"],
  },
  {
    title: "Python PKI Certificate System",
    filter: "Foundations",
    label: "Applied security",
    summary: "An educational PKI simulator covering certificate creation, trust chains, encrypted requests and revocation.",
    stack: "Python · cryptography · RSA · AES · X.509 · CSRs · CRLs",
    build: "I separated Root CA, Sub-CA and client responsibilities and used hybrid encryption so AES handled the payload while RSA protected the session key.",
    proof: "It shows secure-system reasoning and the ability to explain why different cryptographic primitives are combined.",
    href: "https://github.com/Charlie-Qi394/pki-certificate-system-python",
    questions: ["Why use RSA and AES together?", "How is a certificate chain checked?", "What would production require?"],
  },
  {
    title: "AI Graph Search Algorithms",
    filter: "Foundations",
    label: "Algorithms",
    summary: "A tested Python CLI for BFS, DFS, Greedy Best-First Search and A* over CSV graph inputs.",
    stack: "Python · CSV · CLI design · pytest · BFS · DFS · A*",
    build: "I implemented multiple search strategies, validated inputs and tested direct paths, unreachable goals, reverse paths and A* optimality.",
    proof: "It is a compact example of structured problem-solving and makes the trade-offs between speed, memory, completeness and path quality visible.",
    href: "https://github.com/Charlie-Qi394/ai-graph-search-algorithms",
    questions: ["When is BFS enough?", "What makes A* useful?", "How did I test edge cases?"],
  },
];
