import {useEffect,useRef} from 'react';
import {ArrowLeft,ArrowUpRight} from 'lucide-react';
import {portfolioProjects} from './projects';
import {projectNarratives} from './projectNarratives';
export const projectLink=p=>'#project/'+p.href.split('/').pop();
const diagrams={
 'integrated-formulation-optimisation-tool':[{page:6,title:'Formulation architecture: from evidence to deterministic decisions',description:'Excel, CSV and PDF specifications enter the reviewed data workflow. Linear optimisation and constraints produce a feasible formulation with deterministic risk bands.'}],
 'careops-ai':[{page:5,title:'CareOps architecture: controlled business actions',description:'The language model reaches validated business tools through MCP. Permissions, validation and confirmation checks control consequential actions.'}],
 'ai-regulatory-knowledge-assistant':[{page:7,title:'Regulatory RAG: grounding language in evidence',description:'A question is embedded, relevant material is retrieved from pgvector, and the answer is grounded in those sources with citations.'}],
 'computer-vision-cnn-segmentation':[{page:8,title:'Computer vision within the ML and software stack',description:'Original portfolio overview covering classical image processing, CNN classification and semantic segmentation, alongside the other foundation projects.'}],
 'pki-certificate-system-python':[{page:8,title:'Applied security within the ML and software stack',description:'Original portfolio overview includes the educational PKI simulator, trust chains, revocation and the cryptographic primitives used.'}],
 'seq2seq-recipe-generation-nlp':[{page:8,title:'Seq2Seq within the ML and software stack',description:'Original portfolio overview compares LSTM encoder-decoder models with and without attention, alongside the other foundation projects.'}]
};
const context=[{page:2,title:'Software positioning'},{page:3,title:'The system boundary'},{page:4,title:'Choosing an AI architecture'},{page:9,title:'Technical architecture blueprint'},{page:10,title:'Domain experience'},{page:11,title:'Engineering and business value'}];
function Diagram({item}){const src=`${import.meta.env.BASE_URL}reference-deck/page-${String(item.page).padStart(2,'0')}.jpg`;return <figure className="detail-diagram"><figcaption><h3>{item.title}</h3>{item.description&&<p>{item.description}</p>}<a href={src} target="_blank" rel="noreferrer">Open full-size diagram <ArrowUpRight size={15}/></a></figcaption><a href={src} target="_blank" rel="noreferrer" aria-label={`Enlarge ${item.title}`}><img src={src} alt={item.description||item.title} loading="lazy" width="2103" height="1174"/></a></figure>}
export default function ProjectDetails({slug,light}){const p=portfolioProjects.find(p=>p.href.split('/').pop()===slug);const heading=useRef(null);const narrative=projectNarratives.find(n=>n.href===p?.href);useEffect(()=>{window.scrollTo(0,0);heading.current?.focus({preventScroll:true});document.title=p?`${p.title} | Charlie Qi`:'Project not found | Charlie Qi';return()=>{document.title='Charlie Qi | AI Engineering & Biotech R&D';};},[slug,p]);return <div className={`living-site detail-site${light?' light':''}`}><main className="project-detail"><nav className="detail-nav" aria-label="Project navigation"><a href="#projects"><ArrowLeft size={18}/>Back to projects</a><a href="mailto:charlieqi2017@gmail.com?subject=Resume%20request">Résumé on request <ArrowUpRight size={15}/></a></nav>{!p?<h1 ref={heading} tabIndex={-1}>Project not found</h1>:<><header className="detail-header"><span className="eyebrow">CHARLIE QI / PROJECT DEEP DIVE</span><h1 ref={heading} tabIndex={-1}>{p.title}</h1><p>{narrative?.summary||p.bullets[0]}</p><div className="work-stack">{p.stack}</div><a className="text-link" href={p.href} target="_blank" rel="noreferrer">Explore source code <ArrowUpRight size={17}/></a></header><section className="detail-explanation" aria-label="Implementation overview"><div><h2>What I built</h2><p>{narrative?.build||p.bullets[1]}</p></div><div><h2>Why it matters</h2><p>{narrative?.proof||'A complete local workflow connects discovery, transparent matching, original résumé selection and review-controlled application assistance. Matching is deterministic; submission remains manual.'}</p></div></section>{diagrams[slug]?.map(item=><Diagram key={item.page} item={item}/>)}{slug==='charlie-job-application-os'&&<section className="job-detail-flow"><h2>From discovery to human review</h2><ol><li>Public employer feeds are imported, deduplicated and versioned.</li><li>Deterministic scoring ranks jobs against the candidate profile.</li><li>Pass and like decisions persist; résumé selection preserves the original PDF.</li><li>Apply Assist fills supported fields. The user reviews and submits.</li></ol></section>}{narrative?.questions&&<section className="detail-questions"><h2>Engineering questions behind the build</h2><ul>{narrative.questions.map(question=><li key={question}>{question}</li>)}</ul></section>}<details className="context-deck"><summary>Explore the original portfolio architecture and domain context</summary><p>These shared diagrams describe the wider portfolio, rather than the architecture of this project alone.</p>{context.map(item=><Diagram key={item.page} item={item}/>)}</details><footer><a href="#projects"><ArrowLeft size={16}/>Back to all projects</a><a href={p.href} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></footer></>}</main></div>}
